parameters:
#    metadata.example.class: Ant\MetadataBundle\Example

services:
#    metadata.example:
#        class: %metadata.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
